### PR TITLE
Remove trailing lines as well

### PR DESCRIPTION
**Pull request by greimel**
solves #92

### CODE REVIEW

**Comment by greimel** [comment]
I think this should now handle all trailing `#md` `#nb` `#jl` plus their negations.

**Comment by johnnychen94** [comment]
What would happen when we write down some julia codes while it's filtered to markdown...

```julia
using Test #md
```

The only reason I see supporting tailing `#src` is to make editors highlight syntax correctly.

**Comment by greimel** [comment]
It should move to a code chunk in markdown!

## Example

`source.jl`: 
```julia
N = 1_000
x = rand(N)

#jl # Test convergence of the mean to the expected value
using Test #jl
@test mean(x) - 0.5 < 1e-4 #jl

#md # Let's look at the convergence of the mean to the expected value
using Plots #md
plot(cumsum(x)) #md
```

`script.jl`: (e.g. as a generated test file)
```julia
N = 1_000
x = rand(N)

# Test convergence of the mean to the expected value
using Test
@test mean(x) - 0.5 < 1e-4
```

`markdown.md`: 
`````julia
```
N = 1_000
x = rand(N)
```

Let's look at the convergence of the mean to the expected value

```
using Plots
plot(cumsum(x))
```
`````
 This `.md` file can then be weaved to html, capturing the plot.

## Reasons why I want this

* Syntax highlighting (as you said)
* I want to be able to actually run the initial source file while developing

**Comment by fredrikekre** [comment]
Thanks for the PR. I cleaned it up a bit, removed trailing tokens and added tests.

**Pull request merged**
