### PR TITLE
Add the option allow_errors.

### LINKED ISSUE #201: Option to capture errors?
I'm using *Literate.jl* to work on some class material, and in specific cases, I would like a code block to result in an error -- this is mostly to walk students through reading error messages.

Is there a way to keep error messages (possibly on a per-chunk basis)?

### PR DESCRIPTION
**Pull request by tpapp**
Fixes #201.

### CODE REVIEW

**Comment by tpapp** [comment]
I think the docs CI failure is unrelated, I can fix the manifest if needed though.

**Comment by fredrikekre** [comment]
Thanks, I haven't reviewed it but perhaps `continue_on_error` would be more descriptive? Because that is what will happen, right?

**Comment by tpapp** [comment]
Thanks, I renamed the argument.

Another open question is how to show that error: currently it just falls back to `show`, we could use `showerror`, and maybe precede that with an `ERROR: ` as that is more familiar to users.

Please review when you have the time, this is a minor change but would make it much easier for me to write a tutorial I am working on.

**Comment by fredrikekre** [comment]
Thanks, I added a changelog entry. I have another feature in the pipeline that I will finish and then release this with version 2.20.

**Pull request merged**
