### PR TITLE
Strike-through dead link

### PR DESCRIPTION
**Pull request by briochemc**
The link that is struck through is dead.

I was reading the documentation before trying to use Literate.jl and saw this dead link. I'm not sure how to replace it so I just struck it out and submitted this PR, hoping to make it easy for you to spot and edit yourself if you want! 🙂

### CODE REVIEW

**Comment by fredrikekre** [comment]
@Datseris are you still using the method described here? Could you point me to the new locations and then lets make it an commit-specific URL.

**Comment by Datseris** [comment]
Hello,

yeah I am still using it. Sorry for not remembering this. The files mentioned in the documentation are:

* https://github.com/JuliaDynamics/TimeseriesPrediction.jl/blob/master/docs/src/stexamples.jl
* https://github.com/JuliaDynamics/TimeseriesPrediction.jl/blob/master/docs/make.jl

the actual example files (that are then processed by literate) are here:

* https://github.com/JuliaDynamics/TimeseriesPrediction.jl/tree/master/examples

The rest of the links are correct.

**Comment by briochemc** [comment]
I proposed an update for you guys. Not sure why it made a double commit though. (There was a GitHub-interface bug when I pressed the `commit` button and there are no changes in the https://github.com/fredrikekre/Literate.jl/pull/60/commits/50ab066cf57164dd7a870a7e9c03d86698903fa2 commit.)

**Comment by Datseris** [comment]
But @fredrikekre has a valid point. It is best to  get the links in their canonical form:

* https://github.com/JuliaDynamics/TimeseriesPrediction.jl/blob/dcb080376a7861716147c04e45c473f55bb9a078/docs/src/stexamples.jl
* https://github.com/JuliaDynamics/TimeseriesPrediction.jl/blob/dcb080376a7861716147c04e45c473f55bb9a078/docs/make.jl
* https://github.com/JuliaDynamics/TimeseriesPrediction.jl/tree/dcb080376a7861716147c04e45c473f55bb9a078/examples

**Comment by briochemc** [comment]
Like so?

**Comment by briochemc** [comment]
Should I do something differently here?

**Comment by fredrikekre** [comment]
No, I'll have a look.

**Comment by fredrikekre** [comment]
@datseris is there a reason you don’t have any versioned docs?

**Comment by Datseris** [comment]
not really. I don't want to spend more time on that documentation however.

**Pull request merged**
